### PR TITLE
Use FindDataMapInfo instead of FindDataMapOffs

### PR DESCRIPTION
**Pull request by shavitush**
G:\scripting\include\smlib/clients.inc(1056) : warning 234: symbol
"FindDataMapOffs" is marked as deprecated: Use FindDataMapInfo instead,
or HasEntProp if you just want to check for existence.

### CODE REVIEW

**Comment by nikooo777** [comment]
bump, can this be looked into please?

**Comment by peace-maker** [comment]
Please update this branch without all the whitespace removals. You can create a seperate PR if you want them to be removed.

**Comment by shavitush** [comment]
Alright; after this is merged, will you be fine with a PR to rewrite everything to transitional syntax?

**Comment by peace-maker** [comment]
You missed the weapons.inc :wink: 
The `GetClientAuthString` call was fixed in a different PR already. #37

> Alright; after this is merged, will you be fine with a PR to rewrite everything to transitional syntax?

Sure! After that is done, we can work out nice methodmaps to use.

**Comment by shavitush** [comment]
uh i'll start a new pull request, sorry (i'm not a git expert)

**Pull request closed without merging**
