### PR TITLE
Update deprecated function GetClientAuthString to GetClientAuthId

### PR DESCRIPTION
**Pull request by victorngl**

### CODE REVIEW

**Comment by Bara20** [comment]
Take a look at this commit:
https://github.com/bcserv/smlib/commit/17a4ab55951c825960068956b3f8c9d6bde1fd3c

**Comment by victorngl** [comment]
Thank you, I got it.

**Comment by peace-maker** [comment]
You don't need to use those preprocessor workarounds, because GetClientAuthId also exists in sourcemod 1.6.

**Comment by victorngl** [comment]
I do not quite understand how you want to proceed with the functions that are outdated, I just added the preprocessor for versions 1.5 down.

**Comment by peace-maker** [comment]
I'd go the way of only supporting compiler versions which belong to supported sourcemod versions. You can't run sourcemod 1.5 on most games, so we shouldn't care about it. Just change it to GetClientAuthId without any conditionals around it.

**Comment by victorngl** [comment]
Ok, I did it.

**Comment by WildCard65** [comment]
You may also want to update the travis file to remove 1.5 from being used to compile SMLib

**Pull request merged**
