### PR TITLE
Fix ammo bug with csgo (#31)

### PR DESCRIPTION
**Pull request by Bara20**

### CODE REVIEW

**Comment by berni2288** [comment]
I just dumped netprops and see that the old one is gone indeed, so I think this code change is fine and doesn't break more than it fixes.
Please adjust the codestyle and commit --amend, so I can merge this (Don't negate comparisons where possible):

```
stock Weapon_GetPrimaryAmmoCount(weapon)
{
	if (GetEngineVersion() == Engine_CSGO) {
		return GetEntProp(weapon, Prop_Data, "m_iPrimaryReserveAmmoCount");
	} else {
		return GetEntProp(weapon, Prop_Data, "m_iPrimaryAmmoCount");
	}
}
```

Thanks, Berni

**Comment by Bara20** [comment]
Done.

**Comment by IdleGandalf** [comment]
I think he meant that you replace that unlikes (!=) with likes (==) and adjust the adjacent code properly.

**Comment by berni2288** [comment]
Please format the code according to my example, then I will merge this, thanks!

**Comment by runningcore** [comment]
Hello,
i changed my weapons.inc to the "fix" which was posted by Bara20 but it doesn't works.
The primary clip was empty but the reload clip was full.

Maybe i forgot something but take a look please:
my steps:

change weapons.inc ->
recompile plugins -> 
put plugins on server -> 
restart server
= still got the problem with the ammo.

**Comment by berni2288** [comment]
Ok, I implemented the weapon functions a few years ago.
But If I remember right - correct me if I'm wrong - The reserve ammo always got stored in the players entity for each weapon type in the property ```m_iAmmo```. That's why I wrote the functions ```Client_GetWeaponPlayerAmmo``` and ```Client_GetWeaponPlayerAmmoEx```.  I think this is what got changed by Valve now. The reserve ammo is now saved in the weapon itself and not the player entity anymore.

So my preferred solution would be to write new functions in weapons.inc, like Weapon_GetPrimaryReserveAmmo, Weapon_SetPrimaryReserveAmmo, Weapon_GetSecondaryReserveAmmo, Weapon_SetSecondaryReserveAmmo and then change Client_GetWeaponPlayerAmmo and Client_GetWeaponPlayerAmmoEx to check with FindSendPropOffs if the property m_iPrimaryReserveAmmoCount exists in the weapon and then use the old way or call the new functions. This way it will also work for other games automatically if they get updated.

**Comment by runningcore** [comment]
So,

sounds logic but my knowledge in that part is close to 0.

**Comment by runningcore** [comment]
Hey.

Could you please try to implement a new style to set the ammo in cs:go i need that.

Thx
Runningcore

**Comment by runningcore** [comment]
i also could pay a bit for it. :o

**Pull request closed without merging**
